# Generated by Django 3.2.3 on 2021-05-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.BooleanField(blank=True, null=True)),
                ('longitude', models.BooleanField(blank=True, null=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapp.territory')),
            ],
        ),
    ]
